[build]
  publish = "/"
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Headers to enable PWA
  for = "/manifest.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"

  for = "/service-worker.js"
    [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "18"
