[build]
  publish = "/"
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "18"
